CREATE OR REPLACE TABLE DATABASE.SCHEMA.WEBSITES_FINAL_TABLE AS
WITH CTE1 AS (
    (
    -- Argentina
    SELECT WEBSITE, WEBSITE_QUALITY_SCORE, TRUE AS IS_SUCCESS, '' AS ERROR_MESSAGE, 'ARG' AS COUNTRY
    FROM DATABASE.SCHEMA.WEBSITE_QUALITY_SCORES_ARG
    ) UNION ALL (
    SELECT WEBSITE, -1 AS QUALITY_SCORE, FALSE AS IS_SUCCESS, status AS ERROR_MESSAGE, 'ARG' AS COUNTRY
    FROM DATABASE.SCHEMA.WEBSITE_SCRAPED_DATA_ARG
    WHERE STATUS <> 'Success'
    ) UNION ALL (
    
    -- Brazil
    SELECT WEBSITE, WEBSITE_QUALITY_SCORE, TRUE AS IS_SUCCESS, '' AS ERROR_MESSAGE, 'BRA' AS COUNTRY
    FROM DATABASE.SCHEMA.WEBSITE_QUALITY_SCORES_BRA
    ) UNION ALL (
    SELECT WEBSITE, -1 AS QUALITY_SCORE, FALSE AS IS_SUCCESS, status AS ERROR_MESSAGE, 'BRA' AS COUNTRY
    FROM DATABASE.SCHEMA.WEBSITE_SCRAPED_DATA_BRA
    WHERE STATUS <> 'Success'
    ) UNION ALL (
    
    -- Colombia
    SELECT WEBSITE, WEBSITE_QUALITY_SCORE, TRUE AS IS_SUCCESS, '' AS ERROR_MESSAGE, 'COL' AS COUNTRY
    FROM DATABASE.SCHEMA.WEBSITE_QUALITY_SCORES_COL
    ) UNION ALL (
    SELECT WEBSITE, -1 AS QUALITY_SCORE, FALSE AS IS_SUCCESS, status AS ERROR_MESSAGE, 'COL' AS COUNTRY
    FROM DATABASE.SCHEMA.WEBSITE_SCRAPED_DATA_COL
    WHERE STATUS <> 'Success'
    ) UNION ALL (
    
    -- Mexico
    SELECT WEBSITE, WEBSITE_QUALITY_SCORE, TRUE AS IS_SUCCESS, '' AS ERROR_MESSAGE, 'MEX' AS COUNTRY
    FROM DATABASE.SCHEMA.WEBSITE_QUALITY_SCORES_MEX
    ) UNION ALL (
    SELECT WEBSITE, -1 AS QUALITY_SCORE, FALSE AS IS_SUCCESS, status AS ERROR_MESSAGE, 'MEX' AS COUNTRY
    FROM DATABASE.SCHEMA.WEBSITE_SCRAPED_DATA_MEX
    WHERE STATUS <> 'Success'
    ) UNION ALL (
    
    -- Canada
    SELECT WEBSITE, WEBSITE_QUALITY_SCORE, TRUE AS IS_SUCCESS, '' AS ERROR_MESSAGE, 'CAN' AS COUNTRY
    FROM DATABASE.SCHEMA.WEBSITE_QUALITY_SCORES_CAN
    ) UNION ALL (
    SELECT WEBSITE, -1 AS QUALITY_SCORE, FALSE AS IS_SUCCESS, status AS ERROR_MESSAGE, 'CAN' AS COUNTRY
    FROM DATABASE.SCHEMA.WEBSITE_SCRAPED_DATA_CAN
    WHERE STATUS <> 'Success'
    ) UNION ALL (

    -- Jamaica
    SELECT WEBSITE, WEBSITE_QUALITY_SCORE, TRUE AS IS_SUCCESS, '' AS ERROR_MESSAGE, 'JAM' AS COUNTRY
    FROM DATABASE.SCHEMA.WEBSITE_QUALITY_SCORES_JAM
    ) UNION ALL (
    SELECT WEBSITE, -1 AS QUALITY_SCORE, FALSE AS IS_SUCCESS, status AS ERROR_MESSAGE, 'JAM' AS COUNTRY
    FROM DATABASE.SCHEMA.WEBSITE_SCRAPED_DATA_JAM
    WHERE STATUS <> 'Success'
    )
)
SELECT 
    COUNTRY,
    WEBSITE,
    IS_SUCCESS,
    ERROR_MESSAGE,
    WEBSITE_QUALITY_SCORE,
FROM CTE1 
;